### ISSUE TITLE
basic configuration: Error: url must be an URL address

### ISSUE THREAD

**Issue by sajadghawami** [pmb0/express-sharp#192]
hey there,

thank you very much for your work!

I got a problem with a very simple configuration:

```js
const sellerProductUploadDirectory = path.join(__dirname, '../upload/sellerProductImage');
app.use(express.static(sellerProductUploadDirectory));
app.use(
  '/upload/sellerProductImage',
  expressSharp({
    imageAdapter: new FsAdapter(sellerProductUploadDirectory),
  })
);

```

When trying to access the page i get the following for *some* images and not all:

```
node_1      | GET /upload/sellerProductImage/I8bKvIgxn-_default-product.jpg.jpg 400 30.998 ms - 261
node_1      | Error: url must be an URL address
node_1      |     at /backend/node_modules/express-sharp/src/middleware/validator.middleware.ts:21:14
```

This url seems to be fine: `http://localhost:8080/upload/sellerProductImage/FrGn0UIUI-fernando-meloni-va6b5ag3Jvo-unsplash.jpg.jpg`

This url is not working: `http://localhost:8080/upload/sellerProductImage/i6va5p7dE-1060-536x354-blur_2.jpg.jpg`

When i remove the middleware, both images work without a problem.

Any help would be appreciated!

**Comment by sajadghawami** [comment]
So i found out that an underscore is causing this error!

Any quick fixes?

**Comment by pmb0** [comment]
Hello, I'm trying to reproduce the problem now and will get back to you.

**Comment by sajadghawami** [comment]
hey @pmb0 

thanks! It really seems to be a problem of filenames and urls. I changed all filenames to be "url-friendly" but i am still getting the same error for this:

`zade4np6qh-bardokat-designs-makramee-schlusselanhanger-noa-hellgrau.jpg`

but not for this filename:

`zdakz8zor6-robert-bye-tg36rvceqng-unsplash.jpg`


And i am not sure what is causing the error in the first filename, since it does not have any invalid characters.

Thank you very much!

**Comment by pmb0** [comment]
The problem is fixed with https://github.com/pmb0/express-sharp/commit/be9fbeb52b745a11572472b30518c7ac522e7515. A release will follow shortly.

**Comment by sajadghawami** [comment]
Thanks! Did you see this one:

> hey @pmb0
> 
> thanks! It really seems to be a problem of filenames and urls. I changed all filenames to be "url-friendly" but i am still getting the same error for this:
> 
> `zade4np6qh-bardokat-designs-makramee-schlusselanhanger-noa-hellgrau.jpg`
> 
> but not for this filename:
> 
> `zdakz8zor6-robert-bye-tg36rvceqng-unsplash.jpg`
> 
> And i am not sure what is causing the error in the first filename, since it does not have any invalid characters.
> 
> Thank you very much!



Here i am not even using a underscore and still getting the same error

**Comment by pmb0** [comment]
All right, the underline problem is fixed in [v4.2.11](https://www.npmjs.com/package/express-sharp). I'll take a look at the next one now. :)

**Comment by pmb0** [comment]
It turned out that the [validation library used in the background](https://github.com/validatorjs/validator.js/blob/master/src/lib/isURL.js) caused the problems. [I replaced it by now with another mechanism](https://github.com/pmb0/express-sharp/compare/v4.2.11...v4.2.12).

The problem is now fixed in v4.2.12.

**Comment by sajadghawami** [comment]
Works! Thank you very very much!
